Passing the link of empack_env_meta.json file
jupyterlite/xeus pull request #120
Opened 2024-09-25 12:23 UTC by AnastasiaSliusar

This PR is the part of the solution of https://github.com/QuantStack/qs.ai/issues/28
 It includes next changes:
- a new plugin that takes `empack_env_meta` from search url params and this parameter contains a link where empack_env_meta.json file is hosted.
- This link is passed xeus-python during initialization of each kernel.

2024-09-26 07:27 UTC, martinRenou commented on src/index.ts
> +          return empackEnvMetaLink;
In order to stay backward compatible, this should not be the default implementation. The default implementation should stay the same as in the previous implementation.

Some more something like

```suggestion
        return `${kernel_root_url}/empack_env_meta.json`;
```

So `kernel_root_url` should probably be a parameter of `getLink`? It will be up to the provider of the token to use it or not.

2024-09-26 07:30 UTC, martinRenou commented on src/index.ts
> +          return empackEnvMetaLink;
I believe the changes in https://github.com/jupyter-xeus/xeus-python/pull/640/files would not be needed in that case (which is good, let's try our best to make the least changes in pyjs/xeus-python so that we don't break existing deployments which are not pinning xeus-python)

2024-09-27 06:29 UTC, martinRenou commented on src/index.ts
> +         const kernel_root_url = URLExt.join(
👌🏽

2024-10-15 12:09 UTC, trungleduc commented
CI is green!

2024-10-15 13:38 UTC, martinRenou requested changes
Just one nitpicky comment otherwise looks great! Thanks!

2024-10-15 13:38 UTC, martinRenou commented on src/tokens.ts
> +  '@jupyterlite/xeus-python:IEmpackEnvMetaFile'
I believe there is nothing specific to xeus-python in these changes

```suggestion
  '@jupyterlite/xeus:IEmpackEnvMetaFile'
```

2024-10-15 13:38 UTC, martinRenou commented on src/index.ts
> +  id: '@jupyterlite/xeus-python:empack-env-meta',
```suggestion
  id: '@jupyterlite/xeus:empack-env-meta',
```

2024-10-15 14:59 UTC, martinRenou approved these changes
Thanks!

2024-10-15 14:59 UTC, merged